# Generated by Django 3.2.9 on 2022-06-06 18:44

import api.models
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_usuario_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto_documento',
            field=models.ImageField(null=True, upload_to=api.models.nome_arquivo_documento, validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto_usuario',
            field=models.ImageField(null=True, upload_to=api.models.nome_arquivo_foto, validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
