# Generated by Django 3.2.9 on 2022-06-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20220610_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaria',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='diaria',
            name='valor_comissao',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
